name: dlenv
channels:
  - defaults
dependencies:
  - ipython=8.15
  - jupyter=1.0
  - matplotlib=3.7
  - pandas=2.1
  - scikit-learn=1.2
  - pytorch=2.0[build=gpu_cuda118*]
  - torchvision=0.15[build=cuda118*]
